let skills_list = {
  Java: { level: 80, category: 0 },
  Python: { level: 85, category: 0 },
  JavaScript: { level: 85, category: 0 },
  TypeScript: { level: 70, category: 0 },
  C: { level: 80, category: 0 },
  "C++": { level: 80, category: 0 },
  HTML: { level: 95, category: 1 },
  CSS: { level: 95, category: 1 },
  React: { level: 90, category: 1 },
  "React Native": { level: 75, category: 1 },
  Angular: { level: 40, category: 1 },
  Bootstrap: { level: 30, category: 1 },
  "Node.js": { level: 55, category: 2 },
  "Spring Boot": { level: 25, category: 2 },
  Django: { level: 75, category: 2 },
  Flask: { level: 55, category: 2 },
  GraphQL: { level: 40, category: 5 },
  SQL: { level: 80, category: 3 },
  MySQL: { level: 55, category: 3 },
  MongoDB: { level: 65, category: 3 },
  PostgreSQL: { level: 40, category: 3 },
  SQLite: { level: 50, category: 3 },
  TensorFlow: { level: 50, category: 4 },
  NumPy: { level: 75, category: 4 },
  Pandas: { level: 55, category: 4 },
  Git: { level: 70, category: 5 },
  Unix: { level: 80, category: 5 },
  Jira: { level: 75, category: 5 },
  AWS: { level: 30, category: 5 },
  "scikit-learn": { level: 25, category: 4 },
  jQuery: { level: 50, category: 1 },
  GCP: { level: 20, category: 5 },
  SQLAlchemy: { level: 10, category: 3 },
  Sass: { level: 70, category: 1 },
  "MS Access": { level: 75, category: 3 },
  Godot: { level: 60, category: 5 },
};

let categories = ["language", "frontend", "backend", "database", "ai", "other"];

let colors = {
  language: { lightColor: "#ffcccc", darkColor: "#ff6666" },
  frontend: { lightColor: "#ffccef", darkColor: "#ff80d7" },
  backend: { lightColor: "#fff5cc", darkColor: "#ffcf07" },
  database: { lightColor: "#ccffdd", darkColor: "#00ff55" },
  ai: { lightColor: "#ccffff", darkColor: "#00ffff" },
  other: { lightColor: "#efe7dc", darkColor: "#cfb997" },
};

export { skills_list, categories, colors };
